name: "OWASP ZAP Security Scan"
on: [push]

permissions:
  contents: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start ZAP Scan
        run: |
          docker run -t securecodebox/zap zap-baseline.py -t https://4ar9o6xw7e.execute-api.us-east-1.amazonaws.com/prod/ -r zap_report.html
        env:
          DISPLAY: :0

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
